### ISSUE TITLE
Receiving "The ssm module is not supported on Debian/Debian" error

### ISSUE THREAD

**Issue by superking9** [Chaordix/puppet-ssm#6]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, The ssm module is not supported on Debian/Debian. at /etc/puppetlabs/code/environments/master/modules/ssm/manifests/install.pp:32:16

**Comment by TravellingGuy** [comment]
@superking9, this error is not coming from my version of the module. You appear to be using night0wl's fork of the module (https://github.com/night0wl/puppet-ssm/blob/master/manifests/service.pp), which has that specific error message.
